### ISSUE TITLE
Pitch shifting is not done

### ISSUE THREAD

**Issue by AndreyBocharnikov** [dhchoi99/NANSY#13]
Hello and thank you for your amazing work, especially for comments like [this](https://github.com/dhchoi99/NANSY/blob/fcfb646ed64a6612e2e7828a750ade89861fa23b/datasets/functional.py#L107) and [this](https://github.com/dhchoi99/NANSY/blob/fcfb646ed64a6612e2e7828a750ade89861fa23b/datasets/functional.py#L252), they are super helpful.
I have a question about `apply_formant_and_pitch_shift` function from [here](https://github.com/dhchoi99/NANSY/blob/fcfb646ed64a6612e2e7828a750ade89861fa23b/datasets/functional.py#L97), after computing`newMedian` [here](https://github.com/dhchoi99/NANSY/blob/fcfb646ed64a6612e2e7828a750ade89861fa23b/datasets/functional.py#L120), its value is not used anywhere, and Parselmouth function "Shift frequencies" (something like `call(pitch_tier, "Shift frequencies", sound.xmin, sound.xmax, -30, "Hertz")`) is not being called either. Am I missing something?

**Comment by dhchoi99** [comment]
Applying pitch shifting is done with `change_gender` at `apply_formant_and_pitch_shift`.
https://github.com/dhchoi99/NANSY/blob/fcfb646ed64a6612e2e7828a750ade89861fa23b/datasets/functional.py#L134-L137

I'm not that familiar with how parselmouth or praat works with its own `change_gender` functionality, but it is reasonable to think that it could also handle pitch since it has new pitch median argument.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/59348729/187013348-dbbae799-8a8b-49bd-97e7-54880d43155a.png">
